[package]
name = "ylong_time"
version = "1.25.10"
authors = ["d00585364 <duzhaoteng@huawei.com>"]
edition = "2018"
description = "time management module implemented by Rust"
readme = "README.md"
license = "MIT OR Apache-2.0"
repository = "https://open.codehub.huawei.com/innersource/Ylong_Rust/ylong_rs/files?ref=master&filePath=src%2Flib%2Ftime%2Fylong_time"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.153"
