[package]
name = "ylong_box"
version = "1.25.10"
authors = ["l00586455 <louzhihao@huawei.com>"]
edition = "2021"
description = "Box of Ylong std enhancement crates"
readme = "README.md"
repository = "https://open.codehub.huawei.com/innersource/Ylong_Rust/ylong_rs/files?ref=master&filePath=src%2Fstdx%2Fylong_box"
keywords = ["ylong", "std", "box"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ylong_stdx_common = { path = "../ylong_stdx_common", version = "1.25.10" }